services:
  app:
    env_file:
      - path: .env
        required: true
      - path: .env.override
        required: true
    build:
      context: ..
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - USE_SENTRY=${USE_SENTRY}
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - ..:/app/source
